# Generated by Django 2.1.4 on 2019-04-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
