# Generated by Django 2.1.4 on 2019-04-30 15:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190413_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Body',
            field=tinymce.models.HTMLField(),
        ),
    ]
